=== jelenamiletic/vaccination-project/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:in="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje" 
    targetNamespace="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje" elementFormDefault="qualified" >
    <xs:element name="Interesovanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DrzavljaninOpcija">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Drzаvljаnin Republike Srbije"/>
                            <xs:enumeration value="Strani drzаvljаnin sa boravkom u RS"/>
                            <xs:enumeration value="Strani drzаvljаnin bez boravka u RS"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="JMBG">
                    <xs:simpleType>
                        <xs:restriction base = "xs:string">
                            <xs:pattern value="\d{13}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ime" type="xs:string"/>
                <xs:element name="Prezime" type="xs:string"/>
                <xs:element name="AdresaElektronskePoste">
                    <xs:simpleType>
                        <xs:restriction base="xs:string"> 
                                <xs:pattern value="[^@]+@[^\.]+\..+"/> 
                            </xs:restriction>
                    </xs:simpleType>
		        </xs:element>
                <xs:element name = "BrojMobilnogTelefona">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="06\d{8}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name = "BrojFiksnogTelefona">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="011\d{6}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name = "Opstina" type="xs:string"/>
                <xs:element name="VakcinaOpcija">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Pfizer-BioNTech"/>
                            <xs:enumeration value="Sputnik V (Gamaleya истраживачки центар)"/>
                            <xs:enumeration value="Sinopharm"/>
                            <xs:enumeration value="AstraZeneca"/>
                            <xs:enumeration value="Moderna"/>
                            <xs:enumeration value="Било која"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="DavalacKrviOpcija">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Dа"/>
                            <xs:enumeration value="Nе"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jelenamiletic/vaccination-project/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:Interesovanje xmlns:in="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje interesovanje.xsd">
    <in:DrzavljaninOpcija>Drzаvljаnin Republike Srbije</in:DrzavljaninOpcija>
    <in:licneInformacije>
        <in:JMBG>3553355353533</in:JMBG>
        <in:PunoIme>
            <ct:Ime>Daniel</ct:Ime>
            <ct:Prezime>Bozanic</ct:Prezime>
        </in:PunoIme>
        <in:AdresaElektronskePoste>test@gmail.com</in:AdresaElektronskePoste>
        <in:BrojMobilnogTelefona>0635678901</in:BrojMobilnogTelefona>
        <in:BrojFiksnogTelefona>011518556</in:BrojFiksnogTelefona>
        <in:Opstina>Sabac</in:Opstina>
    </in:licneInformacije>
    <in:VakcinaOpcija>Pfizer-BioNTech</in:VakcinaOpcija>
    <in:DavalacKrviOpcija>Nе</in:DavalacKrviOpcija>
</in:Interesovanje>
