=== jelenamiletic/vaccination-project/vakcinacija/vakcinacija/data/xsd/izvestaj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:iz="http:///www.ftn.uns.ac.rs/vakcinacija/izvestaj"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"
    targetNamespace="http:///www.ftn.uns.ac.rs/vakcinacija/izvestaj" elementFormDefault="qualified">
    <xs:import schemaLocation="CommonTypes.xsd"
               namespace="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes" />
    <xs:element name="Izvestaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "PeriodIzvestaja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "OdDatum" type = "xs:date"/>
                            <xs:element name = "DoDatum" type = "xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "BrojPodnetihDokumenata">
                	<xs:complexType>
				  		<xs:simpleContent>
				    		<xs:extension base="iz:BrojPodnetihDokumenata">
						      <xs:attribute name="property" type = "xs:string"/>
						      <xs:attribute name="datatype" type = "xs:string"/>
				    		</xs:extension>
				  		</xs:simpleContent>
					</xs:complexType>
                </xs:element>
                <xs:element name = "ZahteviZaDigitalniSertifikat">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "BrojPrimljenih">
                            	<xs:complexType>
							  		<xs:simpleContent>
							    		<xs:extension base="iz:BrojPrimljenih">
									      <xs:attribute name="property" type = "xs:string"/>
									      <xs:attribute name="datatype" type = "xs:string"/>
							    		</xs:extension>
							  		</xs:simpleContent>
								</xs:complexType>
                            </xs:element>
                            <xs:element name = "BrojIzdatih">
                            	<xs:complexType>
							  		<xs:simpleContent>
							    		<xs:extension base="iz:BrojIzdatih">
									      <xs:attribute name="property" type = "xs:string"/>
									      <xs:attribute name="datatype" type = "xs:string"/>
							    		</xs:extension>
							  		</xs:simpleContent>
								</xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "UkupanBrojDatihDoza" type = "xs:positiveInteger"/>
                <xs:element name = "KolicnaDozaPoRednomBroju" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "RedniBroj" type = "xs:positiveInteger"/>
                            <xs:element name = "BrojDatihDoza" type = "xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name = "RaspodelaDozaPoProizvodjacu" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "Proizvodjac" type = "ct:Proizvodjac"/>
                            <xs:element name = "BrojDatihDoza" type = "xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:anyURI"/>
    		<xs:attribute name="vocab" type="xs:string"/>
            <xs:attribute name = "DatumIzdavanja" type = "xs:date"/>
        </xs:complexType>
        <xs:key name="RedniBrojKljuc">
            <xs:selector xpath="iz:KolicnaDozaPoRednomBroju"/>
            <xs:field xpath="iz:RedniBroj"/>
        </xs:key>
        <xs:key name="ProizvodjacKljuc">
            <xs:selector xpath="iz:RaspodelaDozaPoProizvodjacu"/>
            <xs:field xpath="iz:Proizvodjac"/>
        </xs:key>
    </xs:element>
    <xs:simpleType name="BrojPodnetihDokumenata">
    	<xs:restriction base = "xs:positiveInteger"/>
    </xs:simpleType>
    <xs:simpleType name = "BrojPrimljenih">
    	<xs:restriction base = "xs:positiveInteger"/>
    </xs:simpleType>
    <xs:simpleType name = "BrojIzdatih">
    	<xs:restriction base = "xs:positiveInteger"/>
    </xs:simpleType>
</xs:schema>

=== jelenamiletic/vaccination-project/vakcinacija/data/xml/izvestaj.xml
<?xml version="1.0" encoding="UTF-8"?>
<iz:Izvestaj 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:iz="http:///www.ftn.uns.ac.rs/vakcinacija/izvestaj"  
    xmlns:addr="http://www.ftn.uns.ac.rs/rdf/izvestaj"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/izvestaj/predicate/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http:///www.ftn.uns.ac.rs/vakcinacija/izvestaj ../xsd/izvestaj.xsd"
    DatumIzdavanja = "2022-09-11"
    vocab="http://www.ftn.uns.ac.rs/rdf/izvestaj/" 
    about="http://www.ftn.uns.ac.rs/rdf/izvestaj/2021-08-01/2021-09-01">
    <iz:PeriodIzvestaja>
        <iz:OdDatum>2021-08-01</iz:OdDatum>
        <iz:DoDatum>2021-09-01</iz:DoDatum>
    </iz:PeriodIzvestaja>
    <iz:BrojPodnetihDokumenata property = "pred:brojPodnetihDokumenata" datatype = "xs:positiveInteger">2758</iz:BrojPodnetihDokumenata>
    <iz:ZahteviZaDigitalniSertifikat>
        <iz:BrojPrimljenih property = "pred:brojPrimljenih" datatype = "xs:positiveInteger">456</iz:BrojPrimljenih>
        <iz:BrojIzdatih property = "pred:brojIzdatih" datatype = "xs:positiveInteger">428</iz:BrojIzdatih>
    </iz:ZahteviZaDigitalniSertifikat>
    <iz:UkupanBrojDatihDoza>3225</iz:UkupanBrojDatihDoza>
    <iz:KolicnaDozaPoRednomBroju>
            <iz:RedniBroj>1</iz:RedniBroj>
            <iz:BrojDatihDoza>1789</iz:BrojDatihDoza>
    </iz:KolicnaDozaPoRednomBroju>
    <iz:KolicnaDozaPoRednomBroju>
        <iz:RedniBroj>2</iz:RedniBroj>
        <iz:BrojDatihDoza>1276</iz:BrojDatihDoza>
    </iz:KolicnaDozaPoRednomBroju>
    <iz:KolicnaDozaPoRednomBroju>
        <iz:RedniBroj>3</iz:RedniBroj>
        <iz:BrojDatihDoza>160</iz:BrojDatihDoza>
    </iz:KolicnaDozaPoRednomBroju>
    <iz:RaspodelaDozaPoProizvodjacu>
        <iz:Proizvodjac>Pfizer-BioNTech</iz:Proizvodjac>
        <iz:BrojDatihDoza>1625</iz:BrojDatihDoza>
    </iz:RaspodelaDozaPoProizvodjacu>
    <iz:RaspodelaDozaPoProizvodjacu>
        <iz:Proizvodjac>Sinopharm</iz:Proizvodjac>
        <iz:BrojDatihDoza>1100</iz:BrojDatihDoza>
    </iz:RaspodelaDozaPoProizvodjacu>
    <iz:RaspodelaDozaPoProizvodjacu>
        <iz:Proizvodjac>Sputnik V (Gamaleya истраживачки центар)</iz:Proizvodjac>
        <iz:BrojDatihDoza>356</iz:BrojDatihDoza>
    </iz:RaspodelaDozaPoProizvodjacu>
    <iz:RaspodelaDozaPoProizvodjacu>
        <iz:Proizvodjac>AstraZeneca</iz:Proizvodjac>
        <iz:BrojDatihDoza>144</iz:BrojDatihDoza>
    </iz:RaspodelaDozaPoProizvodjacu>
</iz:Izvestaj>
