=== jelenamiletic/vaccination-project/vakcinacija/vakcinacija/data/xsd/potvrda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:po="http:///www.ftn.uns.ac.rs/vakcinacija/potvrda"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"
    targetNamespace="http:///www.ftn.uns.ac.rs/vakcinacija/potvrda" elementFormDefault="qualified"
    attributeFormDefault="qualified">
    <xs:import schemaLocation="CommonTypes.xsd"
        namespace="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"/>
    <xs:element name="Potvrda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sifra" type="xs:string"/>
                <xs:element name="LicneInformacije">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PunoIme" type="ct:PunoIme"/>
                            <xs:element name="DatumRodjenja" type="xs:date"/>
                            <xs:element name="Pol" type="ct:Pol"/>
                            <xs:element name="JMBG" type="ct:JMBG"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="InformacijeOVakcinacijama" maxOccurs="unbounded" minOccurs="2">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BrojDoze" type="xs:positiveInteger"/>
                            <xs:element name="DatumDavanja" type="xs:date"/>
                            <xs:element name="Serija" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ZdravstvenaUstanova" type="xs:string"/>
                <xs:element name="VakcinaPrveDveDoze" type="ct:Proizvodjac"/>
                <xs:element name="Vakcine" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BrojDoze">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:minInclusive value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Vakcina" type="ct:Proizvodjac"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DatumIzdavanja" type="xs:date"/>
                <xs:element name="QR" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="BrojDozeKljuc">
            <xs:selector xpath="po:Vakcine"/>
            <xs:field xpath="po:BrojDoze"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== jelenamiletic/vaccination-project/vakcinacija/data/xml/potvrda.xml
<?xml version="1.0" encoding="UTF-8"?>
<po:Potvrda
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:po="http:///www.ftn.uns.ac.rs/vakcinacija/potvrda"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http:///www.ftn.uns.ac.rs/vakcinacija/potvrda ../xsd/potvrda.xsd" 
    xmlns:addr="http://www.ftn.uns.ac.rs/rdf/potvrda"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/potvrda/predicate/"
    vocab="http://www.ftn.uns.ac.rs/rdf/potvrda/" 
    about="http://www.ftn.uns.ac.rs/rdf/potvrda/3553355353532_1">
    <po:Sifra>VAX-123</po:Sifra>
    <po:LicneInformacije>
        <po:PunoIme>
            <ct:Ime>Petar</ct:Ime>
            <ct:Prezime>Markovic</ct:Prezime>
        </po:PunoIme>
        <po:DatumRodjenja>1990-08-01</po:DatumRodjenja>
        <po:Pol>Muski</po:Pol>
        <po:JMBG property = "pred:jmbg" datatype = "xs:string">3553355353532</po:JMBG>
    </po:LicneInformacije>
    <po:InformacijeOVakcinama>
        <po:BrojDoze>1</po:BrojDoze>
        <po:DatumDavanja>2021-02-02</po:DatumDavanja>
        <po:Serija>PFI-55609</po:Serija>
    </po:InformacijeOVakcinama>
    <po:ZdravstvenaUstanova>DOM ZDRAVLJA NOVI SAD</po:ZdravstvenaUstanova>
    <po:VakcinaPrveDveDoze property = "pred:VakcinaPrveDveDoze" datatype = "xs:string">Pfizer-BioNTech</po:VakcinaPrveDveDoze>
    <po:DatumIzdavanja>2021-05-05</po:DatumIzdavanja>
    <po:QR>http://www.ftn.uns.ac.rs/</po:QR>
</po:Potvrda>

=== jelenamiletic/vaccination-project/potvrda.xml
<?xml version="1.0" encoding="UTF-8"?>
<po:Potvrda xmlns:po="http:///www.ftn.uns.ac.rs/vakcinacija/potvrda"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http:///www.ftn.uns.ac.rs/vakcinacija/potvrda potvrda.xsd">
    <po:Sifra>VAX-123</po:Sifra>
    <po:LicneInformacije>
        <po:PunoIme>
            <ct:Ime>Petar</ct:Ime>
            <ct:Prezime>Markovic</ct:Prezime>
        </po:PunoIme>
        <po:DatumRodjenja>1990-08-01</po:DatumRodjenja>
        <po:Pol>Muski</po:Pol>
        <po:JMBG>3553355353532</po:JMBG>
    </po:LicneInformacije>
    <po:InformacijeOVakcinacijama>
        <po:BrojDoze>1</po:BrojDoze>
        <po:DatumDavanja>2021-02-02</po:DatumDavanja>
        <po:Serija>PFI-55609</po:Serija>
    </po:InformacijeOVakcinacijama>
    <po:InformacijeOVakcinacijama>
        <po:BrojDoze>2</po:BrojDoze>
        <po:DatumDavanja>2021-03-02</po:DatumDavanja>
        <po:Serija>PFI-66609</po:Serija>
    </po:InformacijeOVakcinacijama>
    <po:InformacijeOVakcinacijama>
        <po:BrojDoze>3</po:BrojDoze>
        <po:DatumDavanja>2021-10-02</po:DatumDavanja>
        <po:Serija>SINO-76609</po:Serija>
    </po:InformacijeOVakcinacijama>
    <po:ZdravstvenaUstanova>DOM ZDRAVLJA NOVI SAD</po:ZdravstvenaUstanova>
    <po:VakcinaPrveDveDoze>Pfizer-BioNTech</po:VakcinaPrveDveDoze>
    <po:Vakcine>
        <po:BrojDoze>3</po:BrojDoze>
        <po:Vakcina>Sinopharm</po:Vakcina>
    </po:Vakcine>
    <po:DatumIzdavanja>2021-05-05</po:DatumIzdavanja>
    <po:QR>http://www.ftn.uns.ac.rs/</po:QR>
</po:Potvrda>
