=== jelenamiletic/vaccination-project/vakcinacija/vakcinacija/data/xsd/sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:se="http:///www.ftn.uns.ac.rs/vakcinacija/sertifikat"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"
    targetNamespace="http:///www.ftn.uns.ac.rs/vakcinacija/sertifikat" elementFormDefault="qualified">
    <xs:import schemaLocation="CommonTypes.xsd"
        namespace="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"/>
    <xs:element name="Sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="BrojSertifikata" type="xs:string"/>
                <xs:element name="DatumVremeIzdavanja" type="xs:dateTime"/>
                <xs:element name="QR" type="xs:string"/>
                <xs:element name="LicneInformacije">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PunoIme" type="ct:PunoIme"/>
                            <xs:element name="DatumRodjenja" type="xs:date"/>
                            <xs:element name="Pol" type="ct:Pol"/>
                            <xs:element name="JMBG">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ct:JMBG">
                                            <xs:attribute name="property" type = "xs:string"/>
                                            <xs:attribute name="datatype" type = "xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name = "BrojPasosa">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ct:BrojPasosa">
                                            <xs:attribute name="property" type = "xs:string"/>
                                            <xs:attribute name="datatype" type = "xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Vakcinacija" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BrojDoze" type="xs:positiveInteger"/>
                            <xs:element name="TipVakcine">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ct:Proizvodjac">
                                            <xs:attribute name="property" type = "xs:string"/>
                                            <xs:attribute name="datatype" type = "xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="DatumDavanja" type="xs:date"/>
                            <xs:element name="Proizvodjac" type="xs:string"/>
                            <xs:element name="Serija" type="xs:string"/>
                            <xs:element name="ZdravstvenaUstanova" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Test">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="ImeTesta" type="xs:string"/>
                            <xs:element name="VrstaUzorka" type="xs:string"/>
                            <xs:element name="ProizvodjacTesta" type="xs:string"/>
                            <xs:element name="DatumVremeUzorkovanja" type="xs:dateTime"/>
                            <xs:element name="DatumVremeIzdavanjaRezultata" type="xs:dateTime"/>
                            <xs:element name="Rezultat">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ct:RezultatTesta">
                                            <xs:attribute name="property" type = "xs:string"/>
                                            <xs:attribute name="datatype" type = "xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Laboratorija" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:anyURI"/>
    		<xs:attribute name="vocab" type="xs:string"/>
        </xs:complexType>
        <xs:key name="BrojDozeKljuc">
            <xs:selector xpath="se:Vakcinacija"/>
            <xs:field xpath="se:BrojDoze"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== jelenamiletic/vaccination-project/vakcinacija/vakcinacija/data/xml/sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<po:Sertifikat
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:po="http:///www.ftn.uns.ac.rs/vakcinacija/sertifikat"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http:///www.ftn.uns.ac.rs/vakcinacija/sertifikat ../xsd/sertifikat.xsd">
    <po:BrojSertifikata>SERT-3848837820</po:BrojSertifikata>
    <po:DatumVremeIzdavanja>2021-11-26T21:32:52</po:DatumVremeIzdavanja>
    <po:QR>http://www.ftn.uns.ac.rs/</po:QR>
    <po:LicneInformacije>
        <po:PunoIme>
            <ct:Ime>Petar</ct:Ime>
            <ct:Prezime>Markovic</ct:Prezime>
        </po:PunoIme>
        <po:DatumRodjenja>1990-08-01</po:DatumRodjenja>
        <po:Pol>Muski</po:Pol>
        <po:JMBG>3553355353532</po:JMBG>
        <po:BrojPasosa>040503921</po:BrojPasosa>
    </po:LicneInformacije>
    <po:Vakcinacija>
        <po:BrojDoze>1</po:BrojDoze>
        <po:TipVakcine>Pfizer-BioNTech</po:TipVakcine>
        <po:DatumDavanja>2021-08-02</po:DatumDavanja>
        <po:Proizvodjac>BIONTECH MANUFACTURING GMBH</po:Proizvodjac>
        <po:Serija>PFI-55609</po:Serija>
        <po:ZdravstvenaUstanova>DOM ZDRAVLJA NOVI SAD</po:ZdravstvenaUstanova>
    </po:Vakcinacija>
    
    <po:Test>
        <po:ImeTesta>SARS-CoV-2 RT</po:ImeTesta>
        <po:VrstaUzorka>Krv</po:VrstaUzorka>
        <po:ProizvodjacTesta>BIONTECH MANUFACTURING GMBH</po:ProizvodjacTesta>
        <po:DatumVremeUzorkovanja>2021-11-26T21:32:52</po:DatumVremeUzorkovanja>
        <po:DatumVremeIzdavanjaRezultata>2021-11-26T21:32:52</po:DatumVremeIzdavanjaRezultata>
        <po:Rezultat>Negativan</po:Rezultat>
        <po:Laboratorija>Dom Zdravlja Zvezdara</po:Laboratorija>
    </po:Test>  
</po:Sertifikat>

=== jelenamiletic/vaccination-project/vakcinacija/data/xml/sertifikat.xml
<?xml version="1.0" encoding="UTF-8"?>
<se:Sertifikat
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:se="http:///www.ftn.uns.ac.rs/vakcinacija/sertifikat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"
    xsi:schemaLocation="http:///www.ftn.uns.ac.rs/vakcinacija/sertifikat  ../xsd/sertifikat.xsd"
    xmlns:addr="http://www.ftn.uns.ac.rs/rdf/sertifikat"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/sertifikat/predicate/"
    vocab="http://www.ftn.uns.ac.rs/rdf/sertifikat/"
    about="http://www.ftn.uns.ac.rs/rdf/sertifikat/3553355353532">
    <se:BrojSertifikata>SERT-3848837820</se:BrojSertifikata>
    <se:DatumVremeIzdavanja>2021-11-02T21:32:52</se:DatumVremeIzdavanja>
    <se:QR>http://www.ftn.uns.ac.rs/</se:QR>
    <se:LicneInformacije>
        <se:PunoIme>
            <ct:Ime>Petar</ct:Ime>
            <ct:Prezime>Markovic</ct:Prezime>
        </se:PunoIme>
        <se:DatumRodjenja>1990-08-01</se:DatumRodjenja>
        <se:Pol>Muski</se:Pol>
        <se:JMBG property = "pred:jmbg" datatype = "xs:string">3553355353532</se:JMBG>
        <se:BrojPasosa property = "pred:brojPasosa" datatype = "xs:string">040503921</se:BrojPasosa>
    </se:LicneInformacije>
    <se:Vakcinacija>
        <se:BrojDoze>1</se:BrojDoze>
        <se:TipVakcine property = "pred:tipVakcine" datatype = "xs:string">Pfizer-BioNTech</se:TipVakcine>
        <se:DatumDavanja>2021-06-02</se:DatumDavanja>
        <se:Proizvodjac>BIONTECH MANUFACTURING GMBH</se:Proizvodjac>
        <se:Serija>PFI-55609</se:Serija>
        <se:ZdravstvenaUstanova>DOM ZDRAVLJA NOVI SAD</se:ZdravstvenaUstanova>
    </se:Vakcinacija>
    <se:Test>
        <se:ImeTesta>SARS-CoV-2 RT</se:ImeTesta>
        <se:VrstaUzorka>Krv</se:VrstaUzorka>
        <se:ProizvodjacTesta>BIONTECH MANUFACTURING GMBH</se:ProizvodjacTesta>
        <se:DatumVremeUzorkovanja>2021-11-02T21:32:52</se:DatumVremeUzorkovanja>
        <se:DatumVremeIzdavanjaRezultata>2021-11-02T21:32:52</se:DatumVremeIzdavanjaRezultata>
        <se:Rezultat property = "pred:rezultat" datatype = "xs:string">Negativan</se:Rezultat>
        <se:Laboratorija>Dom Zdravlja Zvezdara</se:Laboratorija>
    </se:Test>  
</se:Sertifikat>
