=== jelenamiletic/vaccination-project/sluzbenik/data/xsd/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"
    targetNamespace="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje"
    elementFormDefault="qualified">
    <xs:import schemaLocation="CommonTypes.xsd"
        namespace="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes"/>
    <xs:element name="Interesovanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="LicneInformacije">
                    <xs:complexType>
                        <xs:sequence>
                        	<xs:element name = "Drzavljanstvo">
                        		<xs:complexType>
								  <xs:simpleContent>
								    <xs:extension base="in:Drzavljanstvo">
								      <xs:attribute name="property" type = "xs:string"/>
								      <xs:attribute name="datatype" type = "xs:string"/>
								    </xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
                        	</xs:element>
                            <xs:element name="JMBG">
                            	<xs:complexType>
								  <xs:simpleContent>
								    <xs:extension base="ct:JMBG">
								      <xs:attribute name="property" type = "xs:string"/>
								      <xs:attribute name="datatype" type = "xs:string"/>
								    </xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
                            </xs:element>
                            <xs:element name="PunoIme" type="ct:PunoIme"/>
                            <xs:element name="AdresaElektronskePoste">
                            	<xs:complexType>
								  <xs:simpleContent>
								    <xs:extension base="ct:Email">
								      <xs:attribute name="property" type = "xs:string"/>
								      <xs:attribute name="datatype" type = "xs:string"/>
								    </xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
                            </xs:element>
                            <xs:element name="BrojMobilnogTelefona">
                            	<xs:complexType>
								  <xs:simpleContent>
								    <xs:extension base="ct:BrojMobilnogTelefona">
								      <xs:attribute name="property" type = "xs:string"/>
								      <xs:attribute name="datatype" type = "xs:string"/>
								    </xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
                            </xs:element>
                            <xs:element name="BrojFiksnogTelefona">
                            	<xs:complexType>
								  <xs:simpleContent>
								    <xs:extension base="ct:BrojFiksnogTelefona">
								      <xs:attribute name="property" type = "xs:string"/>
								      <xs:attribute name="datatype" type = "xs:string"/>
								    </xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="OpstinaPrimanja">
                	<xs:complexType>
					  <xs:simpleContent>
					    <xs:extension base="ct:Opstina">
					      <xs:attribute name="property" type = "xs:string"/>
					      <xs:attribute name="datatype" type = "xs:string"/>
					    </xs:extension>
					  </xs:simpleContent>
					</xs:complexType>
                </xs:element>
                <xs:element name="Vakcina">
                	<xs:complexType>
					  <xs:simpleContent>
					    <xs:extension base="ct:Proizvodjac">
					      <xs:attribute name="property" type = "xs:string"/>
					      <xs:attribute name="datatype" type = "xs:string"/>
					    </xs:extension>
					  </xs:simpleContent>
					</xs:complexType>
                </xs:element>
                <xs:element name="DavalacKrvi" type = "xs:boolean"/>
                <xs:element name = "DatumPodnosenja" type = "xs:date" minOccurs = "0"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:anyURI"/>
    		<xs:attribute name="vocab" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="Drzavljanstvo">
	    <xs:restriction base="xs:string">
	        <xs:enumeration value="Drzavljanin Republike Srbije"/>
	        <xs:enumeration value="Strani drzavljanin sa boravkom u RS"/>
	        <xs:enumeration value="Strani drzavljanin bez boravka u RS"/>
	    </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jelenamiletic/vaccination-project/sluzbenik/data/xml/interesovanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:Interesovanje
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:in="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje"
    xmlns:ct="http:///www.ftn.uns.ac.rs/vakcinacija/commonTypes" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:addr="http://www.ftn.uns.ac.rs/rdf/interesovanje"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/interesovanje/predicate/"
    xsi:schemaLocation="http:///www.ftn.uns.ac.rs/vakcinacija/interesovanje ../xsd/interesovanje.xsd"
    vocab="http://www.ftn.uns.ac.rs/rdf/interesovanje/" 
    about="http://www.ftn.uns.ac.rs/rdf/interesovanje/1153355353511"
    >
    <in:LicneInformacije>
        <in:Drzavljanstvo property="pred:drzavljanstvo" datatype="xs:string">Drzavlj–∞nin Republike Srbije</in:Drzavljanstvo>
        <in:JMBG property="pred:jmbg" datatype="xs:string">1153355353511</in:JMBG>
        <in:PunoIme>
            <ct:Ime>Pera</ct:Ime>
            <ct:Prezime>Markuza</ct:Prezime>
        </in:PunoIme>
        <in:AdresaElektronskePoste property="pred:email" datatype="xs:string">test@gmail.com</in:AdresaElektronskePoste>
        <in:BrojMobilnogTelefona property="pred:brojMobilnogTelefona" datatype="xs:string">0635678901</in:BrojMobilnogTelefona>
        <in:BrojFiksnogTelefona property="pred:brojFiksongTelefona" datatype="xs:string">015518556</in:BrojFiksnogTelefona>
    </in:LicneInformacije>
    <in:OpstinaPrimanja property="pred:opstinaPrimanja" datatype="xs:string">Sabac</in:OpstinaPrimanja>
    <in:Vakcina property="pred:vakcina" datatype="xs:string">Pfizer-BioNTech</in:Vakcina>
    <in:DavalacKrvi>false</in:DavalacKrvi>
</in:Interesovanje>
